spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9093/~/testDomain
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      schema-locations: classpath:/h2/schema.sql
      data-locations: classpath:/h2/data.sql
      mode: always

logging.level:
    MELT: debug
    org.hibernate.SQL: debug

server:
  port: 9100
