spring:
  datasource:
    url: jdbc:h2:tcp://MyH2Instance:1521/~./testDomain
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

logging.level:
  MELT: debug
  org.hibernate.SQL: trace

server:
  port: 8080